### ISSUE TITLE
Seems nothing is changed when the theme is appled

### ISSUE THREAD

**Issue by ArmandXiao** [phibr0/obsidian-latex-css#2]
Sorry, this may be a stupid question.

- Is this one a css-theme or css-snippets? Or neither.

Why does it seem to have NO effect in both edit and preview mode.

**Comment by phibr0** [comment]
It is a Snippet which is only applied in PDF's

**Comment by ArmandXiao** [comment]
> Sorry, this may be a stupid question.
> 
> * Is this one a css-theme or css-snippets? Or neither.
> 
> Why does it seem to have NO effect in both edit and preview mode.

By the way, I have installed `Style Setting` plugin, and also tested on a new vault which only has this theme and the required plugin. Still, no change in theming.

**Comment by ArmandXiao** [comment]
> It is a Snippet which is only applied in PDF's

Okie! Thanks.
